import { getCategoryInfo, HAZARD_LEVELS } from './categories';
import type { ReportRow } from './types';

export interface ClaimEvidence {
  summary: string;
  reportId: string;
  category: string;
  locationAddress: string;
  gps: string;
  mapsUrl: string;
  timeline: TimelineEvent[];
  severity: { hazardLevel: string; sizeRating?: string };
  mediaCount: number;
  generatedAt: string;
  fullText: string;
}

export interface TimelineEvent {
  date: string;
  event: string;
  detail?: string;
}

export interface ClaimInput {
  report: ReportRow;
  authorityName?: string;
  claimantName?: string;
  vehicleDamageDescription?: string;
  damageDate?: string;
  estimatedCost?: number;
}

const HR = '═'.repeat(60);

export function generateClaimEvidence(input: ClaimInput): ClaimEvidence {
  const { report, authorityName, claimantName, vehicleDamageDescription, damageDate, estimatedCost } = input;

  const category = getCategoryInfo(report.category);
  const hazard = HAZARD_LEVELS.find((h) => h.key === report.hazard_level);
  const locationAddress =
    [report.address, report.city, report.state].filter(Boolean).join(', ') ||
    `${report.latitude.toFixed(6)}, ${report.longitude.toFixed(6)}`;
  const gps = `${report.latitude.toFixed(6)}, ${report.longitude.toFixed(6)}`;
  const mapsUrl = `https://maps.google.com/?q=${report.latitude},${report.longitude}`;

  const timeline: TimelineEvent[] = [];
  timeline.push({
    date: new Date(report.created_at).toLocaleDateString(),
    event: 'Hazard first reported',
    detail: `${category?.label ?? report.category} reported at ${locationAddress} via Fault Line`,
  });
  if (damageDate) {
    timeline.push({
      date: new Date(damageDate).toLocaleDateString(),
      event: 'Damage incurred',
      detail: vehicleDamageDescription,
    });
  }
  if (report.status !== 'submitted') {
    timeline.push({
      date: new Date(report.updated_at).toLocaleDateString(),
      event: `Status changed to ${report.status}`,
    });
  }

  const generatedAt = new Date().toLocaleString();

  const fullText = `
INSURANCE CLAIM EVIDENCE PACKAGE
${HR}
Generated: ${generatedAt}
${claimantName ? `Claimant: ${claimantName}` : ''}
Report ID: ${report.id}

INCIDENT SUMMARY
${HR}
Hazard type: ${category?.label ?? report.category}
Severity: ${hazard?.label ?? report.hazard_level}${report.size_rating ? ` / ${report.size_rating}` : ''}
Location: ${locationAddress}
GPS coordinates: ${gps}
Google Maps: ${mapsUrl}
First reported: ${new Date(report.created_at).toLocaleDateString()}

${vehicleDamageDescription ? `VEHICLE DAMAGE
${HR}
${vehicleDamageDescription}
${damageDate ? `Incident date: ${new Date(damageDate).toLocaleDateString()}` : ''}
${estimatedCost !== undefined ? `Estimated cost: $${estimatedCost.toFixed(2)}` : ''}

` : ''}TIMELINE
${HR}
${timeline.map((t) => `${t.date} — ${t.event}${t.detail ? `\n  ${t.detail}` : ''}`).join('\n')}

AUTHORITY NOTIFICATION
${HR}
${authorityName ? `Responsible authority: ${authorityName}` : 'Authority: to be determined'}
Report status: ${report.status}
${report.submission_reference ? `Submission reference: ${report.submission_reference}` : ''}

EVIDENCE
${HR}
- GPS-verified location data
- Timestamped community report (${new Date(report.created_at).toISOString()})
- ${report.upvote_count} community upvote${report.upvote_count === 1 ? '' : 's'}
- ${report.confirm_count} community confirmation${report.confirm_count === 1 ? '' : 's'}
- ${report.media.length} photograph${report.media.length === 1 ? '' : 's'} attached
${report.description ? `- Reporter description:\n  "${report.description}"` : ''}

${HR}
This evidence package was generated by Fault Line, a community infrastructure
accountability platform. All timestamps and GPS data are verified against the
original report record. Photos attached below are cryptographically linked to
the time and location stated above.
`.trim();

  return {
    summary: `${category?.label ?? report.category} at ${locationAddress}`,
    reportId: report.id,
    category: category?.label ?? report.category,
    locationAddress,
    gps,
    mapsUrl,
    timeline,
    severity: {
      hazardLevel: hazard?.label ?? report.hazard_level,
      sizeRating: report.size_rating,
    },
    mediaCount: report.media.length,
    generatedAt,
    fullText,
  };
}
