import { NextRequest, NextResponse } from 'next/server';
import { createClient, SupabaseClient } from '@supabase/supabase-js';

// Resend webhook handler.
//
// Setup: Resend dashboard → Webhooks → New webhook
//   URL:    https://fault-line-web.vercel.app/api/webhooks/resend
//   Secret: generated by Resend → paste into Vercel env as RESEND_WEBHOOK_SECRET
//   Events: select email.bounced, email.complained, email.delivered,
//           email.delivery_delayed (all useful for escalation tracking)
//
// On arrival, every event is signed with HMAC SHA-256 using the Svix
// convention (Resend uses Svix under the hood). We verify the signature
// before doing any DB writes.

export const runtime = 'nodejs';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const WEBHOOK_SECRET = process.env.RESEND_WEBHOOK_SECRET || '';

interface ResendWebhookEvent {
  type: string;
  created_at: string;
  data: {
    email_id?: string;
    to?: string[] | string;
    from?: string;
    subject?: string;
    bounce?: {
      type?: string;
      subType?: string;
      message?: string;
    };
    click?: unknown;
    complaint?: { type?: string };
  };
}

export async function POST(req: NextRequest) {
  const rawBody = await req.text();

  // Svix-style signature verification. Headers are svix-id, svix-timestamp,
  // svix-signature (comma-separated "v1,base64_signature" pairs).
  const ok = await verifySignature(req, rawBody);
  if (!ok) {
    return NextResponse.json({ error: 'Invalid signature' }, { status: 401 });
  }

  let event: ResendWebhookEvent;
  try {
    event = JSON.parse(rawBody);
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const messageId = event.data.email_id;
  if (!messageId) {
    // Non-email event (no-op for our purposes).
    return NextResponse.json({ received: true });
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  // Find the escalation_log row this event is about.
  const { data: log } = await supabase
    .from('escalation_log')
    .select('id, authority_id, recipient')
    .eq('external_message_id', messageId)
    .maybeSingle();

  if (!log) {
    // Message we didn't send (or sent before message-id tracking existed).
    // Not an error — just ack.
    return NextResponse.json({ received: true, correlated: false });
  }

  const patch: Record<string, unknown> = {};

  switch (event.type) {
    case 'email.delivered':
      patch.delivered_at = event.created_at;
      patch.status = 'delivered';
      break;
    case 'email.bounced': {
      const bounceType = event.data.bounce?.subType || event.data.bounce?.type || 'unknown';
      const bounceReason = event.data.bounce?.message || 'No reason provided';
      patch.bounced_at = event.created_at;
      patch.bounce_type = bounceType;
      patch.bounce_reason = bounceReason;
      patch.status = 'bounced';
      patch.error_message = `Bounce: ${bounceType} — ${bounceReason}`;
      // Update authority email health.
      if (log.authority_id) {
        await updateAuthorityHealth(supabase, log.authority_id, bounceType);
      }
      break;
    }
    case 'email.complained':
      patch.status = 'complained';
      patch.bounce_type = 'complaint';
      patch.bounce_reason = 'Recipient marked as spam';
      patch.bounced_at = event.created_at;
      if (log.authority_id) {
        await updateAuthorityHealth(supabase, log.authority_id, 'complaint');
      }
      break;
    case 'email.delivery_delayed':
      patch.bounce_type = 'delivery_delayed';
      patch.bounce_reason = event.data.bounce?.message || 'Delivery delayed';
      break;
    default:
      // Other events (sent, opened, clicked) aren't actionable here.
      return NextResponse.json({ received: true, event_type: event.type });
  }

  await supabase.from('escalation_log').update(patch).eq('id', log.id);
  return NextResponse.json({ received: true, log_id: log.id, type: event.type });
}

async function updateAuthorityHealth(
  supabase: SupabaseClient,
  authorityId: string,
  bounceType: string,
) {
  const health =
    bounceType === 'complaint' || bounceType.toLowerCase().includes('hard')
      ? 'hard_bouncing'
      : bounceType === 'delivery_delayed'
        ? 'soft_bouncing'
        : 'soft_bouncing';

  // Read, increment, write.
  const { data: existing } = await supabase
    .from('authorities')
    .select('bounce_count')
    .eq('id', authorityId)
    .maybeSingle();

  await supabase
    .from('authorities')
    .update({
      email_health: health,
      last_bounce_at: new Date().toISOString(),
      bounce_count: ((existing?.bounce_count as number | undefined) ?? 0) + 1,
    })
    .eq('id', authorityId);
}

async function verifySignature(req: NextRequest, rawBody: string): Promise<boolean> {
  if (!WEBHOOK_SECRET) {
    // Webhook secret not configured — refuse all events so we never
    // process unauthenticated payloads. Operator must set RESEND_WEBHOOK_SECRET.
    return false;
  }

  const svixId = req.headers.get('svix-id');
  const svixTimestamp = req.headers.get('svix-timestamp');
  const svixSignature = req.headers.get('svix-signature');

  if (!svixId || !svixTimestamp || !svixSignature) return false;

  // Svix secret format: "whsec_<base64>" — strip prefix.
  const secret = WEBHOOK_SECRET.startsWith('whsec_')
    ? WEBHOOK_SECRET.slice(6)
    : WEBHOOK_SECRET;

  const signedPayload = `${svixId}.${svixTimestamp}.${rawBody}`;

  const keyBytes = Uint8Array.from(atob(secret), (c) => c.charCodeAt(0));
  const key = await crypto.subtle.importKey(
    'raw',
    keyBytes,
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
  const sigBytes = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(signedPayload));
  const expected = btoa(String.fromCharCode(...new Uint8Array(sigBytes)));

  // The header contains one or more "v1,<sig>" pairs separated by spaces.
  const sigs = svixSignature
    .split(' ')
    .map((s) => s.split(',')[1])
    .filter((s): s is string => typeof s === 'string' && s.length > 0);
  return sigs.some((sig) => timingSafeEqual(sig, expected));
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let result = 0;
  for (let i = 0; i < a.length; i++) result |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return result === 0;
}
